### PR TITLE
Perf

### PR DESCRIPTION
**Pull request by js-kyle**
WIP not ready

### CODE REVIEW

**Comment by SubJunk** [comment]
This looks good, what is it waiting on? Can I help finish it?

**Comment by js-kyle** [comment]
@SubJunk I was going to take it a bit further but this could be merged as is and still be good, so maybe lets do that. It would be good to just double check it locally running a web server

**Comment by js-kyle** [comment]
@SubJunk I checked it on a local web server and it looks as expected apart from some images expecting to be server from /images which doesnt work locally

**Comment by SubJunk** [comment]
Here is the current Lighthouse report from https://universalmediaserver-website.herokuapp.com/
image

and here it is from this review app https://universalmed-perf-5weyiqfa09fp.herokuapp.com/
image

Here it is in our production website https://www.universalmediaserver.com/
image

So I'll grab it the after screenshot after this deploys too

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
That's better 
image

**Comment by js-kyle** [comment]
Sweet

**Comment by SubJunk** [comment]
Oh I think I noticed a bug, the arrow on the lower right isn't displaying. Maybe it was using an icon from a library that was removed

**Pull request merged**
